### ISSUE TITLE
Question: Validation for member properties

### ISSUE THREAD

**Issue by Domitnator** [Shazwazza/UmbracoIdentity#121]
First of all: Thanks for creating this package!

I have a question about the MemberProperties. We want to take advantage of the validation rules which are applied to the custom member properties. For instance, making the firstname mandatotry:

![image](https://user-images.githubusercontent.com/13468638/88787018-87628580-d193-11ea-90c3-47caa4ace0b4.png)

We then added the "ValidationMessageFor":

![image](https://user-images.githubusercontent.com/13468638/88786709-23d85800-d193-11ea-9220-c183995ad7b3.png)

But there is no error being added for the firstrname:

![image](https://user-images.githubusercontent.com/13468638/88787302-f6d87500-d193-11ea-9716-89bc6fbcecf1.png)

Is there a way to make this work?

Kind Regards,

Alfred

**Comment by Shazwazza** [comment]
You are sort of mixing 2 different things. Those validation settings on the member type are for editing things in the back office, they do not directly translate to the model used on the front-end but I see that it could be nice to have those settings translate to the MVC validation system via the front-end models on the front-end.

That is really outside the scope of this project though. That model you are referring to comes from here https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity.Web/Views/UmbracoIdentityAccount/Register.cshtml#L18. Similarly the profile model comes from here https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity.Web/Views/UmbracoIdentityAccount/Profile.cshtml#L11. Both of these are part of the Umbraco CMS not part of this project. You can see those methods on the MembershipHelper here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Security/MembershipHelper.cs#L384 and https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Security/MembershipHelper.cs#L443

If you want the member type validation settings to translate into these front-end models you'll need to make a request to the CMS team to implement that. However, you could of course just do this yourself. You have the code for `UmbracoIdentityAccountController.HandleRegisterMember` where you could run any custom validation logic you want. You could also create your own registration model instead of using the CMS one and handle the validation logic yourself there too.
