### ISSUE TITLE
Version compatible with Umbraco 7.15.6

### ISSUE THREAD

**Issue by setsqr** [Shazwazza/UmbracoIdentity#122]
Hi,

I'm investigating using this package on an Umbraco 7(.15.6) site.  I tried doing a Nuget install (`PM > Install-Package UmbracoIdentity`) on a completely fresh Umbraco Starter Kit site and it looks like it's upgraded a bunch of Umbraco stuff to v8.0.0 so there are errors all over the place.  I note the [legacy installation](https://github.com/Shazwazza/UmbracoIdentity/wiki/Legacy-Installation) section of the documentation but that only relates to Umbraco 7.1.6-7.3.0.

Is there a specific version of Identity that needs to be installed to work in Umbraco 7.15.6?

I could well be missing something obvious :)

Many thanks!

**Comment by Shazwazza** [comment]
Doing `Install-Package UmbracoIdentity` will install the latest version of a Nuget package. If you have installed Umbraco via Nuget then it would install the latest compatible version but if you haven't installed Umbraco via Nuget it has no way of knowing what you have installed and will install the latest Umbraco nuget package too, see https://www.nuget.org/packages/UmbracoIdentity . 

This product sort of requires that you install umbraco via nuget because Umbraco is one of it's nuget dependencies. If you haven't installed it by Nuget, it will implicitly install the Umbraco package and overwrite a lot of your files. 

https://www.nuget.org/packages/UmbracoIdentity/6.2.0 is the latest v7 compatible version.

**Comment by Shazwazza** [comment]
Yep that should do it! I suppose if you just do `Install-Package UmbracoIdentity` it will just try to install the latest and whatever dependencies that one requires - which would be version 8. I can't remember if there's a nuget cmd switch that prevent nuget from auto-updating to the latest versions and not just sticking to the range of versions you have installed. In any case, yep just specify the compatible version and it should be fine.
