### ISSUE TITLE
The following errors occurred while attempting to load the app. - The OwinStartupAttribute.FriendlyName value 'UmbracoDefaultOwinStartup' does not match the given value 'UmbracoIdentityStartup' in Assembly 'Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by prysmasoftware** [Shazwazza/UmbracoIdentity#124]
Hi,

I made a fresh install with Umbraco 8.8 and seems to have an issue with this new version.
Is there something that I can change for fix it?

This is the error:

```
The following errors occurred while attempting to load the app.
- The OwinStartupAttribute.FriendlyName value 'UmbracoDefaultOwinStartup' does not match the given value 'UmbracoIdentityStartup' in Assembly 'Umbraco.Web, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
- The given type or method 'UmbracoIdentityStartup' was not found. Try specifying the Assembly.
To disable OWIN startup discovery, add the appSetting owin:AutomaticAppStartup with a value of "false" in your web.config.
To specify the OWIN startup Assembly, Class, or Method, add the appSetting owin:AppStartup with the fully qualified startup class or configuration method name in your web.config.
```

**Comment by prysmasoftware** [comment]
For skip this issue I made this change on the web.config.

```
    <!-- <add key="owin:appStartup" value="UmbracoIdentityStartup" />    -->
    <add key="owin:AutomaticAppStartup" value="true" />
    <add key="owin:appStartup" value="UmbracoDefaultOwinStartup" />

```

But now, I am getting issue for do the register and login:

```
System.NullReferenceException: Object reference not set to an instance of an object. at Umbraco_01.Controllers.UmbracoIdentityAccountController.<HandleRegisterMember>d__18.MoveNext() in Controllers\UmbracoIdentityAccountController.cs:line 375
```

**Comment by Shazwazza** [comment]
I'm unsure what "owin:AutomaticAppStartup" but based on your other errors it sounds like this package didn't install correctly. Can you specify steps to replicate from a vanilla install?

**Comment by prysmasoftware** [comment]
Hi,

Thank you a lot for your time!. For be clear, I opened the VS, made a new empty project, open the nuget console, type Install-Package UmbracoCms and then I typed the nuget command for install the UmbracoIdentity using the nuget tool.

After of that, I got the first issue (the entire umbraco wroken). 

If you need something else, please let me know.

Thank you

**Comment by Shazwazza** [comment]
Hi, I just did exactly that and it worked fine. If you can please try again, maybe something went weird with the install. Ill close for now.

**Comment by prysmasoftware** [comment]
Hi Shazwazza, thank you again for your time.
I tried to do it again and same issue. Anyway no worries, but I will share more details to you.

1. Create a new project on VS
2. Run command in VS, Install-Package UmbracoCms
3. Create a new database in the SQL Server (with a new login user too)
4. Configure Umbraco with the starter kit and use the new database created in the SQL Server
5. Run command in VS,  Install-Package UmbracoIdentity
6. Refresh Umbraco local website and you will get the entire site is broken.

I've the UmbracoIdentity working with the previous Umbraco version (I installed it many times because I am learning with all of this CMS), but seems to be something weird with the latest version of 8.8

Again thank you a lot for your time and reply this! Best regards.
Diego.

**Comment by Shazwazza** [comment]
I think i may have seen this before when people are using the wrong .net framework. Be sure when you create your solution you are using **net framework 4.7.2**

**Comment by WinWinsCoding** [comment]
Hello @prysmasoftware, if you have not resolved this, I have some advice for you.
I was having the exact same issue, on multiple systems. Since I had run into this issue four times in a row, I thought that I would try something different. Unfortunately, I changed three things at once, and have not iterated through each one individually or in combination to find out what the exact issue is.
**These are the three things that I changed, and now it is working fine:**
1. When I went to create the new project in Visual Studio, I noticed that the the "ASP.NET Web Application (.NET Framework)" template that I had chosen previously had the "Visual Basic" tag in its description (along with "Windows", "Cloud", and "Web"). Looking further down in the list, I found a "duplicate" template that is identical to the previous one, except that it had the "C#" tag instead of the "Visual Basic" tag. **This time, I chose the "C#" template for the project**.
2. On the "Create a new ASP.NET Web Application" screen, under the "Advanced" area, **I checked "Configure for HTTPS"**, which on previous attempts I had not checked.
3. On previous installs, I had performed a build (and on at least one, actually run the plain Umbraco site) first, before adding the UmbracoIdentity Nuget package. This time, I simply **created the empty project, added the UmbracoCMS package, then added the UmbracoIdentity package. Only then did I build and run**.
Again, I'm not use which of these three (or which combination of them) was what changed the outcome - I'm just glad that I got it working.
Best of luck to you.
And **thank you, @Shazwazza** , for making this. Hopefully it will be exactly what I need for our new Intranet portal.

**Comment by prysmasoftware** [comment]
Hello @WinWinsCoding!! Thank you a lot for your time and for explain what did you do also I am glad to share the same issue with someone else because I was feel a bit frustrated having this issue only me haha. I've installed UmbracoIdentity many times as exercise and I didn't have any issue. But then with the new Umbraco version I couldn't make it working. Anyway, I will try those steps that you posted above and I hope to have any luck with it.
Again, thank you so much!!
