### ISSUE TITLE
How to access AuthenticationOptions from UmbracoIdentityAccountController

### ISSUE THREAD

**Issue by dhymik** [Shazwazza/UmbracoIdentity#134]
Hello Shannon,

this is not an issue but a question. Not even a question strictly related to UmbracoIdentity only, but I have not found any hint anywhere for this (I am not an Owin wizard yet...):

How can I access the `AuthenticationOptions` object defined in `UmbracoIdentityOwinStartup.cs` inside of 'UmbracoIdentityAccountController'? Andy hint is greatly appreciated.

Thank you very much.

**Comment by dhymik** [comment]
I found a way. In UmbracoIdentityOwinStartup, I pass in the options object into the regenerateIdentityCallback function as an additional parameter.

**Comment by dhymik** [comment]
I made the options into a static object inside of the `UmbracoIdentityOwinStartup` class. This seems like a bad way of going about it to me...

**Comment by Shazwazza** [comment]
Hi, yes statics aren't a great option. Owin is a bit annoying to work with since it sort of operates outside of normal aspnet. You have a few options IIRC, you can store those options in the Properties collection of the authentication provider's 'AuthenticationDescription' object. We do this in Umbraco for some custom information stored alongside the provider, see https://github.com/umbraco/Umbraco-CMS/blob/8ff88f47de07fee4c270d4afe44f2e2e1d31d532/src/Umbraco.Web/Security/AuthenticationOptionsExtensions.cs#L61 which is used here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/AuthenticationController.cs#L126

Alternatively you can store anything you want as a Scoped instance in the OwinContext by just doing something like: `app.CreatePerOwinContext<MyObject>()` and then you can retrieve by `owinCtx.Get<MyObject>();`
