### ISSUE TITLE
LoginInfo is null 

### ISSUE THREAD

**Issue by jeffej01** [Shazwazza/UmbracoIdentity#34]
Hi,
Here's hoping someone can help.  
I've successfully implemented OWIN using google authentication, and everything works just fine.
However, when I try and implement authentication via a third party IdentityServer using OpenIdConnectAuthentication everything appears to be fine until the ExternalLoginCallback at which point GetExternalLoginInfoAsync() is always returning null.
I've read sooo many articles on this and there appears to be a number of reasons this may happen, but none of these help and the fact that the google auth works leads me to believe some thing else is going on.

Debugging seems to indicate the Identity from the Authentication ticket isn't being added to the context.

Any ideas would be greatly appreciated.
Thanks

**Comment by Shazwazza** [comment]
Hi, yes i've seen this issue, it's because the required claims are not being found by UmbracoIdentity. In many cases you might have to perform some claim transformation. Luckily I have some info on Identity Server implementation, this is for the back office but I would wager that it's the same for front-end members. This will also vary depending on how you have set up your JWT claim filters. Here's an example of what I mean with notes:

https://github.com/Shazwazza/IdentityServerTest/blob/master/src/MyIdentityServer.Umbraco/App_Start/UmbracoStandardOwinStartup.cs#L64

And setting up a JWT claim filter (like I have done) will mean you don't get back big ugly claim names:
https://github.com/Shazwazza/IdentityServerTest/blob/master/src/MyIdentityServer.Core/OpenIdExtensions.cs#L33

... this is most likely the problem though because when you do this, the required claim names are no longer there.

Please re-open if you can get this solved.

**Comment by Shazwazza** [comment]
BTW, this is how the GetExternalLoginInfo method works:

```
        private static ExternalLoginInfo GetExternalLoginInfo(AuthenticateResult result)
        {
            if (result == null || result.Identity == null)
            {
                return null;
            }
            var idClaim = result.Identity.FindFirst(ClaimTypes.NameIdentifier);
            if (idClaim == null)
            {
                return null;
            }
            // By default we don't allow spaces in user names
            var name = result.Identity.Name;
            if (name != null)
            {
                name = name.Replace(" ", "");
            }
            var email = result.Identity.FindFirstValue(ClaimTypes.Email);
            return new ExternalLoginInfo
            {
                ExternalIdentity = result.Identity,
                Login = new UserLoginInfo(idClaim.Issuer, idClaim.Value),
                DefaultUserName = name,
                Email = email
            };
        }
```

**Comment by stijnvanbossuyt** [comment]
Any updates on this?

**Comment by stijnvanbossuyt** [comment]
For anyone else getting this issue this solved it for me:

> "Enable the Google+ API. This is one hidden b**** of a gotcha and is the root cause of the problem in the question here - if you don't do this, it's easy to miss that the Request to /account/ExternalLoginCallback includes &error=access_denied, and that's because Google said no to a permissions request OWIN made for the user's Google+ basic profile. I can't tell whose fault this is, Google's or Microsoft's."

-- Chris Moschini

Source: [http://stackoverflow.com/questions/19775321/owins-getexternallogininfoasync-always-returns-null/29921451#29921451](url)

**Comment by Shazwazza** [comment]
Thanks @stijnvanbossuyt for this feedback
