### ISSUE TITLE
A couple of customization questions

### ISSUE THREAD

**Issue by michaelrandrup** [Shazwazza/UmbracoIdentity#48]
Hi @Shazwazza 

I have made a Microsoft Dynamics CRM based User Store for integrating CRM with Web front-ends. Everything is working well, and I now want to use this provider with your project, but I have run into a couple of issues (maybe due to my lack of understanding the inner-workings of the Umbraco Membership system):
## My first approach

My first approach was to just create a sub-class for your Umbraco UserStore, so I can provide my own storage (including the external logins).

**Question**: I can only override two methods of your base UserStore class (Create and Update), which means the identities will not be looked up in Dynamics CRM. Can I get around that?
## My second approach

My second approach was to then override the entire UserManager, but the base class still requires the Umbraco "membershipprovider" (which I am not very familiar with).

**Question 1**: Does Umbraco require that all members be stored in the CMS database as well? (hence the internal membershipprovider reference in your UserStore and UserManager classes).

**Question 2**: Is it possible to just use a _normal_ Owin startup, register my CRM UserStore/UserManager as I would on a regular MVC website? My Idea is that I would create a property on the Page Datatypes to indicate what security should be enforced, and then use a custom global AuthorizationFilter class to resolve if the user has access to the requested page. Is this a vial approach although I then cannot use the built-in backoffice membership system?

My Dynamics CRM UserStore is defined as:

``` C#
public class UserStore<T, S> : IUserStore<T,S>, IUserLoginStore<T, S>, IUserClaimStore<T, S>, IUserEmailStore<T, S>, IUserLockoutStore<T, S>, IUserPasswordStore<T,S>, IUserTwoFactorStore<T, S>, IUserSecurityStampStore<T,S>, IUserPhoneNumberStore<T,S>, IUserRoleStore<T,S>
        where T : CrmIdentityUser<S>, new()
        where S : IEquatable<S>
```

In a _normal_ I would register the UserStore and SignInmanager as:

``` C#
app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);
```

Where the static `ApplicationUserManager.Create` and `ApplicationSignInManager.Create` methods initializes the Dynamics CRM based store.

You can see the implementation of the UserStore here: [UserStore.cs](https://github.com/michaelrandrup/DynamicsCrmIdentity/blob/master/Microsoft.AspNet.Identity.DynamicsCrm/UserStore.cs)

I hope you are able to guide me in the correct direction!

Regards,
Michael

**Comment by Shazwazza** [comment]
Hi, there's a lot of questions in this thread so will try to answer a few (sorry time is in short supply these days!)

It sounds like you have a custom identity provider already based on Dynamics CRM. If you already have a full implementation of of this, you can use it just like you would in a normal MVC site. You will still need to inherit from the Umbraco OWIN startup class (`UmbracoDefaultOwinStartup`) to register all of your managers - this is because Umbraco still requires the back office identity parts to be registered on startup.

Umbraco doesn't require you to use it's membership system for your front-end members and of course if you already have member data elsewhere then you can certainly use that. The only caveat is that the Membership section in the back office won't integrate with your external data and the 'public access' parts of Umbraco content will not work - you'd have to implement your page security yourself (but that's not difficult). 

To give you a little more detail about why Umbraco's Identity implementation has a link to membershipprovider - it's because this is made to be compatible with the legacy ASP.Net membership system so that passwords are hashed between both systems in the same way. If you have your own Identity implementation in place then you don't need to worry about any of this since you membership data is 100% external. 

Hope that helps
