### ISSUE TITLE
Custom User Store Example Requested

### ISSUE THREAD

**Issue by mrbillh** [Shazwazza/UmbracoIdentity#49]
Please put up a skeleton of how to invoke a custom user store.
Just the invocation on configuration and user store class def would be really helpful.

**Comment by Shazwazza** [comment]
When I find some time I'll update these docs with an example: https://github.com/Shazwazza/UmbracoIdentity/wiki/Startup-Configuration#custom-user-store

**Comment by mrbillh** [comment]
Some explanation of what the docs are not helping me to do:

Instead of using Umbraco database to Authenticate, I have a set of methods in a custom dll that provide Authentication.

What I need is to be able to override or control the actions like:
     FindByNameAsync -- really the only one I think I need, because I am not allowing users to be created, or anything else.  The users exist in another system, and are managed there.  I am ok with implementing the rest of that class, if necessary.


So I started working on creating a custom user store - and so far, have this:

I took the NuGet Umbraco Identity GitHub source, and added it as a project to the standard Umbraco 7.4.3 installation.  Modified the web.config as appropriate, added UmbracoIdentityStartup.

My idea is to use the Umbraco Identity project as the start of my custom Identity.

Here is an excerpt from the file 'UmbracoIdentityStartup.cs', in ConfigureServices

        ```   app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>(
                new UmbracoMembersUserStore<UmbracoApplicationMember>(ApplicationContext.Services.MemberService,
                                                                       ApplicationContext.Services.MemberTypeService,
                                                                       ApplicationContext.Services.MemberGroupService,
                                                                       new IdentityEnabledMembersMembershipProvider(),
                                                                       new ExternalLoginStore()), ApplicationContext);```

This is what I have been able to figure out from looking at the source, and given the signature listed under the Custom user store heading.

This gives a runtime error - Cannot use ASP.Identity with UmbracoMembersUserStore when the password format is not Hashed.

So, it seems the UmbracoMembersUserStore.cs , in UmbracoIdentity is not a good base to start with for a custom user store.

What about creating a new user store ??

Ok, how about this --
 ```
    public class CustomUserStore : IUserStore<UmbracoApplicationMember>
    {
         //    CreateAsync, DeleteAsync, FindByNameAsync, etc. implemented here
    }
```

Nope, not going to work -- UmbracoApplicationMember must be convertible to Microsoft.AspNet.Identity.IUser<string>

Wait !!! there is this - UmbracoIdentityMember, how about that ??  Sorry, same error.

So what should the declaration for a custom user store look like in order to play nice with UmbracoIdentity ??

**Comment by Shazwazza** [comment]
Hi,

Just to be clear about what this library is: This is a custom ASP.Net Identity implementation for front-end members (not back office users) which uses Umbraco's native membership data storage and is compatible with Umbraco's legacy ASP.Net Membership implementation.

Based on what you say here:

> The users exist in another system, and are managed there.

It really sounds like you want to implement an entire custom Identity provider - really nothing to do with Umbraco or UmbracoIdentity. I'll also stress that this library is for front-end members and *not* back office users, if you need this functionality for back office users, there is a whole different process for that which this library is not responsible for. The only reasons you'd really have a custom user store for this library is as per docs (https://github.com/Shazwazza/UmbracoIdentity/wiki/Startup-Configuration#custom-user-store) 

>  if you need your user store to support more features than what is shipped by default. 

... this is really stating if you would like these things that are currently not implemented: https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues#not-implemented-yet 

 >if you want to have a custom IExternalUserStore instance that stores external logins in your own custom db table instead of SQLCE

This library's intentions are not so you can just replace the entire user store with non native Umbraco data. The error you are getting `Cannot use ASP.Identity with UmbracoMembersUserStore when the password format is not Hashed` is because this library is specifically designed to be compatible with the legacy ASP.Net membership providers, thus the password hashing done in this implementation is based on the ASP.Net membership hashing (see: https://github.com/Shazwazza/UmbracoIdentity/wiki/Known-Issues#passwords) . If you don't replace the password hasher this library requires that the membership provider registered in config uses hashed passwords, here's where the default is set: https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/UmbracoMembersUserManager.cs#L71

If you are implementing a totally custom ASP.Net identity provider than i would suggest the following:

* See if there is already one made for your data source ( I assume based on your email that this is Active Directory )
* You can definitely reference the code in this project as a starting point to create a custom ASP.Net identity implementation, but the reality is that a ton of the code in this project is not going to help you since a lot of this very specific to Umbraco's member storage, specific primary key types, password formats and hashing, etc... . Since your member data is stored 100% outside of Umbraco most of what you'll need is going to be custom.

When I wrote this library, i referenced quite a lot of code from the EntityFramework ASP.Net identity implementation, you could also look there for inspiration. Here's a couple of other great links about creating custom identity implementations:

* http://odetocode.com/blogs/scott/archive/2014/01/20/implementing-asp-net-identity.aspx
* http://www.asp.net/aspnet/samples/aspnet-identity

I hope some of this info can guide you in the right direction. Let me know if you have other questions.

**Comment by mrbillh** [comment]
Thank you for your reply.
I understand that this library is for front end only.  That is what I want.
Thanks for the tip about the password hasher, although I was already aware of that.

**Comment by mrbillh** [comment]
I have forked this project, and am using it as a base to get the functionality I need.
In order to meet some deadlines, I am hacking some stuff together.
I hope to be able to give questions / feedback that is useful to this library soon.

**Comment by Shazwazza** [comment]
If you want to create a bare bones custom user store, you'll need to start with the basic models. Have a look at the base model classes (the ones that are the basis of `UmbracoIdentityMember`) models like:

* `IdentityMember<T>` https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity/Models/IdentityMember.cs
* `IdentityMemberRole<T>`

etc...

Those are the basic models (taken from EF source) that a custom user store, etc... will use. You can certainly use these models. It is beyond me why MS didn't include these basic models in a project outside of EF. So if you want the MS versions of these models you need to reference the entire EF ASP.Net Identity project - i chose not to do that and used my own models.

Then depending on your primary key type - if it's AD then I'll assume it's a large custom ID so you'd probably want to use a `string`. UmbracoIdentity uses an `int` because that's how the data is stored, this is why `UmbracoIdentityMember` implements all of these base classes with `int` keys.  If you have string keys, you'll need to copy the `UmbracoIdentityMember ` class and change the key type - please note that the observable portions of this class are a custom implementation I made in order to support the ASP.Net Identity model and how it works. EF and other implementations might use a different technique.
