### ISSUE TITLE
User Member and Azure AD B2C integration

### ISSUE THREAD

**Issue by elvogel** [Shazwazza/UmbracoIdentity#52]
I have a fresh Umbraco 7.4.x project and I'm looking to leverage Azure AD B2C for storing and managing Members. I wanted to see if I can get some confirmation as to what I need to do in order to implement this correctly:
1. build custom UmbracoMembersRoleManager, RoleStore, UserManager, UserStore and IdentityEnabledMembersMembershipProvider that leverage GraphAPI to get/set user data
2. Build a custom controller to handle the registration and login processes, which in turn send external calls to the AD B2C to obtain the authentication tokens

Does that sound accurate?

Thank you!

**Comment by Shazwazza** [comment]
If you want to use Azure AD B2C you should use the it's OAuth OpenIDConnect provider. 

If you go down the path that you've listed above for # 1, you are creating your own ASP.NET Identity provider which will have nothing to do with this project (i.e. you wouldn't really be using any parts of this project since that wouldn't make sense). It would be quite a large amount of work trying to create a full Identity implementation to wrap Azure AD B2C but you're welcome to do that if you want.

Just to be clear about what this library is: This is a custom ASP.Net Identity implementation for front-end members (not back office users) which uses Umbraco's native membership data storage and is compatible with Umbraco's legacy ASP.Net Membership implementation. It also supports plugging in OAuth providers for using external identity servers as the authentication mechanism. https://github.com/Shazwazza/UmbracoIdentity/wiki/External-Authentication-(OAuth)

**Comment by elvogel** [comment]
I understand that it's for the front-end member and not the back office - that's exactly whom I'm focused on at the moment. I'm also using the sample project you referenced in the documentation update as an implementation model within the Umbraco solution. I think perhaps I was confusing identity with authentication.

Let me see if I can reframe the scenario and work that needs to be done:

- Use AD B2C to register the user with Azure, which looks like it involves making HttpContext.GetOwinContext().Authentication.Challenge calls (or the Umbraco equivalent) according to the sample project

- Use OAuth OpenIDConnect to authenticate the member (similar to above, which I probably need to research)

- Use the OAuth claims retrieve what was stored in Azure AD and use it to sync with the Umbraco membership service


So based on the updated scenario I can:
- implement a custom controller that will let me register/authenticate 
- Upon registration, create/sync the member in Umbraco via MemberService

UmbracoIdentity is for using the ASP.NET Identity model, so if I'm not in need of that ASP.NET Identity anywhere then I should be focusing more on the Umbraco developer documentation than this project.

**Comment by Shazwazza** [comment]
Hi, yes you are on the right track here. If you want to use Azure B2C then the easiest way is to implement an OAuth provider. I have some experience with implementing a B2C provider but I'll say it's not the most straight forward one I've worked with, there are some fiddly bits.

In the umbraco core for the back office, we have a policy to allow people to declare OAuth provider to auto-link local accounts - this is essentially what you are referring to with create/sync the member in Umbraco. However, you probably shouldn't use the MemberService directly and just stick to ASP.Net Identity APIs since that what you'll be dealing with in the OWIN world. You can use the `UmbracoMembersUserManager` to create the Umbraco member data. Unfortunately the auto-link local accounts logic isn't implemented for this library, so yup you'll have to implement that yourself.

The B2C provider also does not return any role information with the initial payload. This may have changed since I last tested but I was told that if i wanted to received any additional information from B2C upon login that you have to use the Graph API to make a query in one of the callbacks in the OAuth provider registration.

I'm not sure if it will help but here is a 'working' implementation of a B2C provider implementation for the umbraco back office - of course since yours is for this project and for front-end members there will be some differences but it might help a bit: https://github.com/Shazwazza/UmbracoScripts/blob/master/src/Identity/AzureADB2C.cs

**Comment by Shazwazza** [comment]
On another note, in response to your comment:

> UmbracoIdentity is for using the ASP.NET Identity model, so if I'm not in need of that ASP.NET Identity anywhere then I should be focusing more on the Umbraco developer documentation than this project.

In order to nicely implement any OAuth provider using OWIN, you're generally going to have to deal with an Identity implementation and since you'll need to sync some information locally you have 2 easy options: Use this library, which means that your sync'd (basic) member info will be available in the umbraco back office and people could create local logins if you want to allow that, or you could use ASP.NET EF Identity provider, but this will not integrate with Umbraco at all.

**Comment by jonathanS8080** [comment]
Hi Shazwazza,
I have looked at your link above regarding the AzureADB2C.cs file and I was wondering if you had this implemented into a working project so I could see how you can register a user to the B2C AD? 
Would this still use the Microsoft Pop up window using the Sign-Up Principle or could I use a custom form?
Plus, I am familiar with a number of the OWIN startup class such as tenant, clientId but not sure where I would find adminClientId and adminClientSecret.
Many thanks
Jon

**Comment by Shazwazza** [comment]
I had it implemented but it's no longer existing, the code for that was moved to that link above (https://github.com/Shazwazza/UmbracoScripts/blob/master/src/Identity/AzureADB2C.cs) in case i needed it in the future.

This library isn't for registering users, that functionality exists in B2C itself or however you've set that up. This integration is just the OAuth integration for authenticating users. IIRC B2C has a few ways to have users sign up and you can 'skin' their forms too. 

It's been quite a while since I've looked at this stuff so off the top of my head I cannot recall exactly what the adminClientId and adminClientSecret was but I'm pretty sure this is used for accessing the graph api only which in that snippet was going to be used to possibly return more user info that the OAuth provider normally returns on authentication (IIRC it doesn't return roles, etc... ). So unless you plan on using the graph api then I don't think you need that, otherwise you'll need to create graph api credentials which is what these values are.

**Comment by lyck** [comment]
Hi @Shazwazza or @elvogel, If you've got it to work :-) 
I'm not quite on how to implement it.
I want to login to Umbraco Using Azure AD
I have downloaded both UmbracoScripts and UmbracoIdentity.

Is it at all possible to use Azure AD for member Login?

What changes must be made in web config?
These values are ok and I can login to other application, It is tested, Azure is ok.

 ```
<add key="ida:ClientId" value=" xx " />
 <add key="ida:AADInstance" value="https://login.microsoftonline.com/" />
 <add key="ida:Domain" value="xxCloud.onmicrosoft.com" /> 
 <add key="ida:TenantId" value=" xx " />
 <add key="ida:PostLoginUrl" value="http://localhost:54028/umbraco" />
``` 

This I am not sure.
`<add key="owin:appStartup" value="UmbracoIdentityStartup" />`

When using Azure AD, I do not need a custom login page, I will of course be routed directly Windows Azure Login. Is it possible? (Of course I can remove it later, what is important is to get to call the correct logic)

I expect that it is the code from AzureADB2C.cs to be used, even though it is for Backoffice and this is not for Backoffice. Is this correct?
I have set public access on the site and create a member group.
I have been almost  able to login in BackOffice, but there is none left menu and it's like, it continues to, load content. Maybe it's because you are not attach to a group?

My question is. How do I get on? I keep being returned to the same articles, which contains, a lot of text and very little about what exactly to do.

Hope you can push me in the right direction.
Thank you!

**Comment by elvogel** [comment]
The code referenced in this discussion isn't actually for the Back Office - it was to get AD B2C working for front-end users in order to give those users an SSO-like experience (in my case anyways). I never did figure out how to make it work successfully, but I also know from my research that securing the back office has been discussed in the Umbraco forum(s) and blogged about:

Securing Umbraco BackOffice with Azure AD
https://www.jdibble.co.uk/blog/securing-umbraco-backoffice-with-azure-active-directory

@Shazwazza had an article about this very thing as well but his website isn't working at the moment.

**Comment by Shazwazza** [comment]
There was a few tricks that were required to get B2C working for the back office, which you'll need to implement for the front-end members too. UmbracoIdentity (this project) ships with Code for the `UmbracoIdentityAccountController` which you'll probably need to modify. B2C requires that you have a custom challenge response sent, in the back office example, this is specified here: https://github.com/Shazwazza/UmbracoScripts/blob/master/src/Identity/AzureADB2C.cs#L191

However, that is a specific ext method to work for the back office, you'd need to modify the custom challenge response directly in the `UmbracoIdentityAccountController`

Unfortunately B2C requires a lot of extra steps when configuring, OOTB UmbracoIdentity probably isn't going to support it explicitly but since UmbracoIdentity ships with all of the code you'd need to modify, you should only require changing a few things. You'll have to very carefully read the B2C docs on what needs to be implemented.

**Comment by NikRimington** [comment]
@Shazwazza , firstly sorry for posting on a closed question but I'm wondering if you can help me. I'll start with the fact that authentication really isn't my strong suit so apologies if what I'm asking is obvious but I couldn't spot it in your examples and links here.

I'm trying to get Azure AD B2C working for Members and I "think" I'm fairly close.

**Setup:**
Umbraco v8.1.1
UmbracoIdentity v7

**Current situation**
I'm getting sent to the Azure AD B2C login page and I authenticate
Callback hits `OnAuthorizationCodeReceived` in my OwinStartupClass
(at the minute this method is basically empty, just some code to stop it erroring)
UmbracoIdentityAccountController ExternalLoginCallback get's hit.

**Problems**
1) What am I meant to put in the OnAuthorizationCodeReceived method, I'm sure I need to do something to store, I'm guessing the JWT token I get back?
2) GetExternalLoginInfoAsync is returning loginInfo with a missing e-mail field. However when I look at the JWT token I get back there is an e-mail claim associated. How do I set this e-mail field so that ExternalLoginCallback can create the Umbraco  member?

I did try and replicate your NaiveSessionCache class but that hit an issue with TokenCache now being a sealed class so it can derive from it, and I ended up down a rabbit hole of not understanding the responses to people talking about the same thing. 

Any help you can provide would be wonderful!

**Comment by Shazwazza** [comment]
@NikRimington I unfortunately can't offer you any quick tips, it's been a very long time since i attempted any B2C integration and even when i did it was just prototyping. I've referenced any of the work I did above and since then I haven't done any work with it. Best of luck, if there's a will there's a way. Would love for anyone that's implemented B2C with OpenIdConnect to blog about it or update the docs here. This library isn't doing anything magical, if you can get it working with OpenIdConnect, you can get it working with this lib.
