### ISSUE TITLE
Installation problem with NUGET with Umbraco 7.5.13...

### ISSUE THREAD

**Issue by biapar** [Shazwazza/UmbracoIdentity#71]
Hi,

I've installed Umbraco 7.5.13 but with your nuget package installation corrupt my Umbraco 7.5.13 installation. It remove Umbraco 7.5.13 and it install 7.5.6.
So after I launch Update-Package UmbracoCms
You need change Umbraco version into your nuget config.

**Comment by Shazwazza** [comment]
This package doesn't do anything with regards to the umbraco version. Did you install Umbraco via Nuget? I suspect the problem is that you are not using Nuget to install Umbraco and then you've installed this package via Nuget which also now installed Umbraco via Nuget (because it's a dependency) over the top of your installation.
