### ISSUE TITLE
Custom Membership provider support

### ISSUE THREAD

**Issue by blachawk** [Shazwazza/UmbracoIdentity#82]
Is there any flexibility in using UmbracoIdentity to authenticating members already existing in an external database? I have an SSO server that handles its own members, and would simply like have Umbraco recognize the members 'there'.  Is this the right package for the job? or perhaps there is an alternative for my goal?

I really don't want to re-create all my members in Umbraco.  I simply want a single database source of members established, and have Umbraco recognize them there.

Thanks for any tips

**Comment by blachawk** [comment]
Still stuck here.  Any help will be greatly appreciated.  Just looking for options.

**Comment by Shazwazza** [comment]
This project is to enable ASP.NET identity functionality for members in Umbraco which is stored in Umbraco's own data storage.

If you have members that exist in your own data storage and you have SSO enabled for that provider, there's nothing stopping you from just integrating OAuth in umbraco with your own provider. 

You need to be more specific about "Umbraco recognize" them? What exactly do you want Umbraco to recognize for your members? 
* The members editor in the back office will only work for Members stored in Umbraco and there's limited functionality for this for implementing your own MembershipProvider and replacing the native Umbraco one.
* The public access portion of Umbraco will only work with the native membership storage of Umbraco. AFAIK it will not work with custom membership providers. But if you wish to implement security for portions of your Umbraco website you can do that the normal MVC way and implement your own controllers for Umbraco (hijacked routes) and integrate your own security

**Comment by Shazwazza** [comment]
There are 2 different things :

* Users == back office users, OAuth integration for Users is built in to Umbraco: https://our.umbraco.org/Documentation/Reference/Security/#custom-oauth-providers 
* Members == front-end members that login to gain access to any resources and pages that you've created. OAuth integration for Members is done by the developer and depends on your requirements, here's some options.  If you have Member data that exists elsewhere there are a couple of options:
   * If you wanted to have an OAuth provider button on your website for members like  "Sign in with MyCompany" and then have a local member created than it will work with this library and since this library ships with Code, you can modify that to suit your needs. All of the OAuth linking is done in the controller that is shipped, for example instead of prompting a newly logged in member with additional details, you could skip that step, or do whatever you wanted: https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity.Web/App_Code/Controllers/UmbracoIdentityAccountController.cs#L93  . This would allow you to have custom membership data stored in Umbraco for this linked member but retain the SSO login with the button. If you don't want to use custom data stored in Umbraco then it will be up to you to integrate managing the member data with your system separately.
   * If you wanted to only have an OAuth provider button on your website for members like "Sign in with MyCompany" then you would use ASP.NET Identity to setup an Auth flow to your OAuth enabled provider and then any custom data retrieval or updates would be up to you to create. Essentially this is the same as having a regular website authenticating with a custom OAuth provider which you can find references for online.
   * Create a custom ASP.NET membership provider that uses your data and replace Umbraco's default "UmbracoMembershipProvider" with your own type. Similarly if you did this, you'd want to replace Umbraco's default "UmbracoRoleProvider" with data from your solution. This does not cover anything to do with OAuth but would let you use the ASP.NET membership provider APIs to perform any login/registration logic if you wanted. For any custom data retrieval that doesn't exist in the membership provider, it would be up to you to integrate your Umbraco solution with your other membership solution.

**Comment by blachawk** [comment]
Many Many Thanks!
