### ISSUE TITLE
Issue with Umbraco Cloud

### ISSUE THREAD

**Issue by yarin12** [Shazwazza/UmbracoIdentity#93]
Hi,
Can I use this installation with Umbraco Cloud? I need it only for membership login. I want the backoffice users still use the Umbraco Cloud while membership users "front-end users" use the Auth0 provider.

I installed and tested a little but I cant make it works. I loss the option for deploying to umbraco cloud in the Content page.

**Comment by Shazwazza** [comment]
I may have actually just encountered a similar problem, i'll see what i can find out

**Comment by Shazwazza** [comment]
Hi, the reason you might be running into this issue is due to the `UmbracoIdentityStartup` owin class. In the `ConfigureMiddleware` method, the base class needs to be called. So at the very end of this method, you need to put: `base.ConfigureMiddleware(app);`

I'll need to fixup the file that is shipped since that line is missing here https://github.com/Shazwazza/UmbracoIdentity/blob/master/src/UmbracoIdentity.Web/App_Code/UmbracoIdentityStartup.cs#L125

**Comment by yarin12** [comment]
Hi Shazwazza, The VS project didnt break. however, the page rendering cast an error on the devtool console. The error said that a signlr page was not founded.

I ended up uninstalling the UmbracoIdentity. Changed my design to use the umbraco membership.

**Comment by Shazwazza** [comment]
That's the exact issue, so the work around is what I wrote above.
