### ISSUE TITLE
type or namespace name 'UmbracoMembersUserManager<>' could not be found

### ISSUE THREAD

**Issue by cdecinkoKnight** [Shazwazza/UmbracoIdentity#98]
Clean creation of a .NET project.  Added Umbraco 7.14 via NuGet with default starter kit.  Site runs with no errors as expected.  Installed UmbracoIdentity via NuGet.  Now, cannot even build the project, getting 12 of this error:

The type or namespace name 'UmbracoMembersUserManager<>' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Shazwazza** [comment]
I cannot replicate.

* I create a new ASP.Net Framework 4.5.2 project in VS, with 'empty' (no mvc, etc..)
* I install nuget package: `Install-Package UmbracoCms -Version 7.14.0`
* Start the site and run the installer
* I install nuget package 'Install-Package UmbracoIdentity`
* Start the site, everything works

what are you doing differently and do you have more information? Maybe you are using a 'website' instead of a 'web app' ? Or maybe you've named your project (and thus your default namespace) to something that conflicts with the default namespace in UmbracoIdentity.

**Comment by cdecinkoKnight** [comment]
Not sure what is wrong.  Using Visual Studio 2015.  I do the exact steps above.  Before I was using .Net 4.7 so I chose 4.5.2 this time.  On the second build/restart I get errors that UmbracoMembersUserManager and UmbracoMembersRoleManager cannot be found.  I can fix that by allowing using UmbracoIdentity to be added to the controller.  But then I get an error about an ambiguous call to GetUserId.  It doesn't know to use the Microsoft version or the UmbracoIdentity version.


![image](https://user-images.githubusercontent.com/46462212/59122917-d5258a00-8910-11e9-9f00-7b732c3eeeb5.png)

**Comment by Shazwazza** [comment]
maybe you can post the code in that controller here? I can't replicate the issue sorry

**Comment by Shazwazza** [comment]
RIght, i think i've been able to replicate, will see what i can do

**Comment by Shazwazza** [comment]
The problem is for some reason that there's ambiguity between microsoft's extension methods and the one shipped with UmbracoIdentity, perhaps this is caused by some owin updates or something along the way.

You can fix this yourself now by just using the MS extensions explicitly so in your `UmbracoIdentityAccountController` replace all instances of `User.Identity.GetUserId<int>()` with `Microsoft.AspNet.Identity.IdentityExtensions.GetUserId<int>(User.Identity)`

I'll get a new release out that fixes this though.

**Comment by Shazwazza** [comment]
Have shipped 6.2.0 https://github.com/Shazwazza/UmbracoIdentity/releases/tag/v6.2.0
